### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by rpelizza** [ProAngular/ngx-gist#7]
I'm using Angular  v15.1.2.
![image](https://user-images.githubusercontent.com/5438017/215296587-ed391bf1-db40-46d8-9314-c700d5812883.png)

I tried install ngx-gist: ng add @proangular/ngx-gist@latest
After, that, an error appears in my terminal:  Package "@proangular/ngx-gist" was found but does not support schematics.
![image](https://user-images.githubusercontent.com/5438017/215296607-e52b4ff0-4d97-4f4d-a9fd-0a4cfbad877f.png)

I imported the module
![image](https://user-images.githubusercontent.com/5438017/215296498-dd930c09-1602-4540-8f0f-aa501132573e.png)

and after ng s:

![image](https://user-images.githubusercontent.com/5438017/215296534-04c85419-318e-442e-af4f-fabcd6a91f12.png)

What did I do wrong?

Ah... and my package.json

![image](https://user-images.githubusercontent.com/5438017/215296569-4c4d3b76-521a-4518-8922-4cbc78f7a9c9.png)

**Comment by CodyTolene** [comment]
Sorry for the late reply, I'll look into this further. It looks like I may have missed a step in the instructions to include `io-ts` or I may need to add it to the peer dependencies here. Thanks for reporting this. 

In the meantime, please try adding `io-ts` to your projects dependencies to see if the issue resolves:
```
"dependencies": {
    ...
    "io-ts": "^2.2.20",
```

**Comment by CodyTolene** [comment]
The following has been added to `peerDependencies`:
```
"io-ts": "^2.2.17",
"io-ts-types": "^0.5.16"
```

Let me know if you have any further issues. Thanks
